### ISSUE TITLE
.RData used for run_survival_random_forest_tcga.R not available in your repo

### ISSUE THREAD

**Issue by risserlin** [mehmetgonen/path2surv#1]
Your code computes over the TCGA data by loading in .RData files with the data.

Do you have a script that pulls the TCGA data and processes it to the required format?
What does the data matrix that you use for the analysis look like?  Can you post an example data file.

Thanks,

**Comment by mehmetgonen** [comment]
TCGA data set has to be in the following format:
* There should be a data frame called **mrna**, and it should have patient ids as row names and gene names as column names. Please note that we log-scale the expression values. If your data is already log-scaled, please get rid of the log-scaling line.
* There should be a data frame called **clinical**, and it should have patient ids as row names and minimally have columns called **vital_status**, **days_to_death**, **days_to_last_followup**, and **days_to_last_known_alive**.
